package services

import (
	"bytes"
	"fmt"
	"image/color"
	"image/jpeg"
	"strings"

	"github.com/fogleman/gg"
	"skelton-api/models"
)

// ImageService handles image generation
type ImageService struct{}

// NewImageService creates a new image service instance
func NewImageService() *ImageService {
	return &ImageService{}
}

// GenerateFolderStructureImage generates a JPG image of the folder structure
func (s *ImageService) GenerateFolderStructureImage(content *models.AIGeneratedContent) ([]byte, error) {
	// Calculate image dimensions based on folder tree depth and size
	treeLines := s.countTreeLines(content.FolderStructure.Tree, 0)
	width := 1200
	height := max(800, treeLines*25+100)

	// Create a new image context
	dc := gg.NewContext(width, height)

	// Set white background
	dc.SetColor(color.White)
	dc.Clear()

	// Add title
	dc.SetColor(color.RGBA{31, 73, 125, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 28); err != nil {
		// Fallback if font not found
		dc.SetColor(color.Black)
	}
	dc.DrawString("Project Folder Structure", 40, 50)

	// Add subtitle
	dc.SetColor(color.RGBA{100, 100, 100, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14); err == nil {
		dc.DrawString("Root: "+content.FolderStructure.RootFolder, 40, 80)
	}

	// Draw folder tree
	dc.SetColor(color.Black)
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 12); err == nil {
		s.drawFolderTree(dc, content.FolderStructure.Tree, 40, 120, 0)
	} else {
		// Fallback to default font
		s.drawFolderTree(dc, content.FolderStructure.Tree, 40, 120, 0)
	}

	// Add footer
	dc.SetColor(color.RGBA{150, 150, 150, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 10); err == nil {
		dc.DrawString("Generated by Skelton API", 40, float64(height-20))
	}

	// Encode to JPEG
	var buf bytes.Buffer
	img := dc.Image()
	err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 95})
	if err != nil {
		return nil, fmt.Errorf("failed to encode image: %w", err)
	}

	return buf.Bytes(), nil
}

// drawFolderTree draws the folder tree on the image
func (s *ImageService) drawFolderTree(dc *gg.Context, nodes []models.FolderNode, x, y float64, level int) float64 {
	lineHeight := 22.0
	indent := 25.0
	currentY := y

	for i, node := range nodes {
		// Draw connector lines
		if level > 0 {
			dc.SetColor(color.RGBA{200, 200, 200, 255})
			dc.DrawLine(x-15, currentY-5, x-5, currentY-5)
			dc.Stroke()
		}

		// Draw icon and text
		icon := ""
		var nodeColor color.Color
		if node.Type == "folder" {
			icon = "📁"
			nodeColor = color.RGBA{0, 100, 200, 255}
		} else {
			icon = "📄"
			nodeColor = color.RGBA{80, 80, 80, 255}
		}

		dc.SetColor(nodeColor)
		text := fmt.Sprintf("%s %s", icon, node.Name)
		dc.DrawString(text, x+float64(level)*indent, currentY)

		currentY += lineHeight

		// Draw children recursively
		if len(node.Children) > 0 {
			// Draw vertical line for children
			if level >= 0 {
				dc.SetColor(color.RGBA{200, 200, 200, 255})
				childrenHeight := float64(s.countTreeLines(node.Children, 0)) * lineHeight
				dc.DrawLine(x+float64(level)*indent+10, currentY-lineHeight+5, x+float64(level)*indent+10, currentY+childrenHeight-lineHeight-5)
				dc.Stroke()
			}
			currentY = s.drawFolderTree(dc, node.Children, x, currentY, level+1)
		}

		// Add spacing between siblings at the same level
		if i < len(nodes)-1 {
			currentY += 3
		}
	}

	return currentY
}

// countTreeLines counts the total number of lines in the tree
func (s *ImageService) countTreeLines(nodes []models.FolderNode, level int) int {
	count := 0
	for _, node := range nodes {
		count++
		if len(node.Children) > 0 {
			count += s.countTreeLines(node.Children, level+1)
		}
	}
	return count
}

// GenerateTechnicalSpecImage generates an image representation of the technical spec
func (s *ImageService) GenerateTechnicalSpecImage(content *models.AIGeneratedContent) ([]byte, error) {
	width := 1200
	height := 2000

	// Create a new image context
	dc := gg.NewContext(width, height)

	// Set white background
	dc.SetColor(color.White)
	dc.Clear()

	// Add title
	dc.SetColor(color.RGBA{31, 73, 125, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32); err != nil {
		dc.SetColor(color.Black)
	}
	dc.DrawString("Technical Specification", 40, 60)

	currentY := 120.0

	// Project Overview
	dc.SetColor(color.RGBA{0, 0, 0, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18); err == nil {
		dc.DrawString("Project Overview", 40, currentY)
		currentY += 30
	}

	dc.SetColor(color.RGBA{50, 50, 50, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12); err == nil {
		dc.DrawString(content.TechnicalSpecification.ProjectOverview.Title, 60, currentY)
		currentY += 25

		// Wrap description text
		wrapped := s.wrapText(content.TechnicalSpecification.ProjectOverview.Description, 100)
		for _, line := range wrapped {
			dc.DrawString(line, 60, currentY)
			currentY += 18
		}
		currentY += 20
	}

	// Architecture
	dc.SetColor(color.RGBA{0, 0, 0, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18); err == nil {
		dc.DrawString("System Architecture", 40, currentY)
		currentY += 30
	}

	dc.SetColor(color.RGBA{50, 50, 50, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12); err == nil {
		dc.DrawString("Pattern: "+content.TechnicalSpecification.SystemArchitecture.Pattern, 60, currentY)
		currentY += 30
	}

	// Technology Stack
	dc.SetColor(color.RGBA{0, 0, 0, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18); err == nil {
		dc.DrawString("Technology Stack", 40, currentY)
		currentY += 30
	}

	dc.SetColor(color.RGBA{50, 50, 50, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12); err == nil {
		dc.DrawString("Backend: "+content.TechnicalSpecification.TechnologyStack.Backend.Name, 60, currentY)
		currentY += 20
		dc.DrawString("Frontend: "+content.TechnicalSpecification.TechnologyStack.Frontend.Name, 60, currentY)
		currentY += 20
		dc.DrawString("Database: "+content.TechnicalSpecification.TechnologyStack.Database.Name, 60, currentY)
		currentY += 20
		dc.DrawString("Messaging: "+content.TechnicalSpecification.TechnologyStack.Messaging.Name, 60, currentY)
		currentY += 30
	}

	// Encode to JPEG
	var buf bytes.Buffer
	img := dc.Image()
	err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 95})
	if err != nil {
		return nil, fmt.Errorf("failed to encode image: %w", err)
	}

	return buf.Bytes(), nil
}

// wrapText wraps text to fit within a maximum width (in characters)
func (s *ImageService) wrapText(text string, maxWidth int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return []string{}
	}

	var lines []string
	currentLine := words[0]

	for _, word := range words[1:] {
		if len(currentLine)+len(word)+1 <= maxWidth {
			currentLine += " " + word
		} else {
			lines = append(lines, currentLine)
			currentLine = word
		}
	}
	lines = append(lines, currentLine)

	return lines
}

// max returns the maximum of two integers
func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// GenerateCombinedImage generates a combined image with both folder structure and tech spec
func (s *ImageService) GenerateCombinedImage(content *models.AIGeneratedContent) ([]byte, error) {
	width := 1600
	treeLines := s.countTreeLines(content.FolderStructure.Tree, 0)
	height := max(1200, treeLines*25+600)

	// Create a new image context
	dc := gg.NewContext(width, height)

	// Set white background
	dc.SetColor(color.White)
	dc.Clear()

	// Main title
	dc.SetColor(color.RGBA{31, 73, 125, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32); err != nil {
		dc.SetColor(color.Black)
	}
	dc.DrawString("Project Architecture & Specification", 40, 50)

	// Draw a vertical divider
	dc.SetColor(color.RGBA{200, 200, 200, 255})
	dc.DrawLine(800, 100, 800, float64(height-50))
	dc.Stroke()

	// Left side - Folder Structure
	dc.SetColor(color.RGBA{0, 0, 0, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 20); err == nil {
		dc.DrawString("Folder Structure", 40, 100)
	}

	dc.SetColor(color.Black)
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 11); err == nil {
		s.drawFolderTree(dc, content.FolderStructure.Tree, 40, 140, 0)
	}

	// Right side - Technical Specification Summary
	dc.SetColor(color.RGBA{0, 0, 0, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 20); err == nil {
		dc.DrawString("Technical Specification", 820, 100)
	}

	currentY := 140.0
	dc.SetColor(color.RGBA{50, 50, 50, 255})
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 11); err == nil {
		// Project info
		dc.DrawString("Project: "+content.TechnicalSpecification.ProjectOverview.Title, 820, currentY)
		currentY += 25

		// Architecture
		dc.SetColor(color.RGBA{0, 0, 0, 255})
		if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 14); err == nil {
			dc.DrawString("Architecture", 820, currentY)
			currentY += 20
		}
		dc.SetColor(color.RGBA{50, 50, 50, 255})
		dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 11)
		dc.DrawString("Pattern: "+content.TechnicalSpecification.SystemArchitecture.Pattern, 820, currentY)
		currentY += 35

		// Technology Stack
		dc.SetColor(color.RGBA{0, 0, 0, 255})
		if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 14); err == nil {
			dc.DrawString("Technology Stack", 820, currentY)
			currentY += 20
		}
		dc.SetColor(color.RGBA{50, 50, 50, 255})
		dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 11)
		dc.DrawString("• Backend: "+content.TechnicalSpecification.TechnologyStack.Backend.Name, 820, currentY)
		currentY += 18
		dc.DrawString("• Frontend: "+content.TechnicalSpecification.TechnologyStack.Frontend.Name, 820, currentY)
		currentY += 18
		dc.DrawString("• Database: "+content.TechnicalSpecification.TechnologyStack.Database.Name, 820, currentY)
		currentY += 18
		dc.DrawString("• Messaging: "+content.TechnicalSpecification.TechnologyStack.Messaging.Name, 820, currentY)
		currentY += 35

		// Deployment
		dc.SetColor(color.RGBA{0, 0, 0, 255})
		if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 14); err == nil {
			dc.DrawString("Deployment", 820, currentY)
			currentY += 20
		}
		dc.SetColor(color.RGBA{50, 50, 50, 255})
		dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 11)
		dc.DrawString("Strategy: "+content.TechnicalSpecification.DeploymentPlan.Strategy, 820, currentY)
		currentY += 18
		dc.DrawString("Infrastructure: "+content.TechnicalSpecification.DeploymentPlan.Infrastructure, 820, currentY)
	}

	// Encode to JPEG
	var buf bytes.Buffer
	img := dc.Image()
	err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 95})
	if err != nil {
		return nil, fmt.Errorf("failed to encode image: %w", err)
	}

	return buf.Bytes(), nil
}
